<?php

namespace AppBundle\Entity\Compta;

use Doctrine\ORM\EntityRepository;

/**
 * RelanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementBancaireRepository extends EntityRepository
{

	public function findByYearAndCompany($year, $company){

		$result = $this->createQueryBuilder('m')
		->leftJoin('AppBundle\Entity\Compta\CompteBancaire', 'co', 'WITH', 'co.id = m.compteBancaire')
		->where('co.company = :company')
		->andWhere('m.date >= :dateDebut and m.date <= :dateFin')
		->setParameter('company', $company)
		->setParameter('dateDebut', $year.'-01-01')
		->setParameter('dateFin', $year.'-12-31')
		->getQuery()
		->getResult();

		return $result;

	}

	public function findByDateAndCompteBancaire($year, $month, $compteBancaire){

		$result = $this->createQueryBuilder('m')
		->where('m.date >= :dateDebut and m.date <= :dateFin')
		->andWhere('m.compteBancaire = :compteBancaire')
		->setParameter('compteBancaire', $compteBancaire)
		->setParameter('dateDebut', $year.'-'.$month.'-01')
		->setParameter('dateFin',  $year.'-'.$month.'-31')
		->orderBy('m.date', 'ASC')
		->getQuery()
		->getResult();

		return $result;

	}

	public function findByCompany($company){

		$result = $this->createQueryBuilder('m')
		->leftJoin('AppBundle\Entity\Compta\CompteBancaire', 'co', 'WITH', 'co.id = m.compteBancaire')
		->where('co.company = :company')
		->setParameter('company', $company)
		->getQuery()
		->getResult();

		return $result;

	}

}
