<?php

namespace AppBundle\Entity\TimeTracker;

use Doctrine\ORM\EntityRepository;

/**
 * TempsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempsRepository extends EntityRepository
{
}
