<?php

namespace AppBundle\Entity\CRM;

use Doctrine\ORM\EntityRepository;

/**
 * BonCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonCommandeRepository extends EntityRepository
{
	public function findByCompany($company){
		$qb = $this->createQueryBuilder('c')
		->leftJoin('AppBundle\Entity\CRM\Opportunite', 'o', 'WITH', 'o.id = c.actionCommerciale')
		->leftJoin('AppBundle\Entity\CRM\Compte', 'co', 'WITH', 'co.id = o.compte')
		->where('co.company = :company')
		->setParameter('company', $company);

		$result = $qb->getQuery()->getResult();
		return $result;
	}
}
