<?php

namespace AppBundle\Entity\CRM;

use Doctrine\ORM\EntityRepository;

/**
 * ImpulsionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpulsionRepository extends EntityRepository
{

	public function findTimespan($timespan, $user){
		$today = date('Y-m-d').'%';

		$query = $this->createQueryBuilder('i')
		->where('i.user = :user')
		->andWhere('i.priseContact IS NULL');

		if('today' == $timespan){
			$query->andWhere('i.date LIKE :today');
			}

		if('week' == $timespan){
			$sunday = date('Y-m-d', strtotime('next sunday'));
			$query
				->andWhere('i.date > :today')
				->andWhere('i.date <= :sunday')
				->setParameter('sunday', $sunday);
		}

		if('late' == $timespan){
			$query 
				->andWhere('i.date < :today');
		}


		$result = $query
		->setParameter('today', $today)
		->setParameter('user', $user)
		->getQuery()
		->getResult();

		return $result;
	}

}
