<?php

namespace AppBundle\Entity\Social;

use Doctrine\ORM\EntityRepository;

/**
 * MerciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerciRepository extends EntityRepository
{
}
