<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecuRepository extends EntityRepository
{
	public function findRefacturablesForCompanyByYear($company, $year){

	  	$qb = $this->createQueryBuilder('r')
	    ->innerJoin('r.user', 'u')
	    ->innerJoin('r.ligneDepense', 'l')
	    ->innerJoin('l.depense', 'd')
	    ->innerJoin('d.noteFrais', 'n')
	    ->where('u.company = :company')
	    ->andWhere('r.date >= :start')
	    ->andWhere('r.date <= :end')
	    ->andWhere('r.refacturable = true')
	    ->andWhere('n.etat = :valide OR n.etat = :rapproche')
	    ->setParameter('company', $company)
	    ->setParameter('valide', 'VALIDE')
	    ->setParameter('rapproche', 'RAPPROCHE')
	    ->setParameter('start', $year.'-01-01')
	    ->setParameter('end',  $year.'-12-31');

	  	return $qb->getQuery()->getResult();
	}
}
