<?php

namespace AppBundle\Entity\Emailing;

use Doctrine\ORM\EntityRepository;

/**
 * CampagneContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagneContactRepository extends EntityRepository
{
}
